coverage:
  status:
    project: # Measures overall project coverage.
      default:
        target: auto
        threshold: 1%
        informational: true # Project coverage for stats only.
    patch: # Only measures lines adjusted in the pull request.
      default:
        target: 80%
        threshold: 5%
        informational: true # Unit tests are now in place; informational while the team adjusts.