fit_path: "fit_mouse.p"
ik_only_path: "ik_only_mouse.p"
data_path: "tests/data/test_mouse_mocap_3600_frames.h5"

n_fit_frames: 250
skip_fit_offsets: False
skip_ik_only: True

mujoco:
  solver: "newton"
  iterations: 1
  ls_iterations: 4
