calibration_path: "synth_calibration.h5"
ik_path: "synth_ik.h5"
data_path: "tests/data/test_synth_1_frames.nwb"

n_calibration_frames: 1
skip_calibration: False
skip_ik: True
infer_qvels: False # Infer qvels from stac output
n_frames_per_clip: 1

mujoco:
  solver: newton
  iterations: 1
  ls_iterations: 4
