fit_path: "fly_treadmill_fit.p"
transform_path: "transform_treadmill.p"
# File is too large to commit
# DL from: https://datadryad.org/stash/dataset/doi:10.5061/dryad.mpg4f4r73
# Actual file: https://datadryad.org/stash/downloads/file_stream/3361804
data_path: "/data/users/eabe/biomech_model/Flybody/datasets/Tuthill_data/wt_berlin_linear_treadmill_dataset.csv"

n_fit_frames: 1800
skip_fit: False
skip_transform: False
gpu: '1'
mujoco:
  solver: "newton"
  iterations: 1
  ls_iterations: 4
