calibration_path: "celegans_calibration.h5"
ik_path: "celegans_ik.h5"
#data_path: "tests/data/test_rodent_mocap_1000_frames.mat"
n_calibration_frames: 500
skip_calibration: False
skip_ik: True
infer_qvels: True # Infer qvels from stac output
n_frames_per_clip: 250

mujoco:
  solver: "newton"
  iterations: 1
  ls_iterations: 4
