#FLY_MODEL
fit_path: "fly_treadmill_fit.p"
ik_only_path: "transform_treadmill.p"
# File is too large to commit
# DL from: https://datadryad.org/stash/dataset/doi:10.5061/dryad.mpg4f4r73
# Actual file: https://datadryad.org/stash/downloads/file_stream/3361804
data_path: "/root/vast/jason/stac-fly/stac-mjx/tests/data/test_fly_treadmill_short.csv"

n_fit_frames: 1800
skip_fit_offsets: False
skip_ik_only: False
gpu: '1'
mujoco:
  solver: "newton"
  iterations: 1
  ls_iterations: 4
