fit_offsets_path: "mouse_arm_fit.p"
ik_only_path: "mouse_arm_ik_only.p"
data_path: "tests/data/points3d_transformed_shorten.h5"
# data_path: "tests/data/test_mouse_mocap_3600_frames.h5"

n_fit_frames: 1
skip_fit_offsets: False
skip_ik_only: True

mujoco:
  solver: "newton"
  iterations: 1
  ls_iterations: 4
