fit_path: "fit_free.p"
transform_path: "transform_free.p"
data_path: "tests/data/test_rodent_mocap_1000_frames.nwb"

n_fit_frames: 1800
skip_fit: False
skip_transform: False

mujoco:
  solver: "newton"
  iterations: 1
  ls_iterations: 4
