user: eabe

# set the directory where the output files get saved
cwd_dir:  /gscratch/portia/${paths.user}/Research/MyRepos/Fly_tracking
base_dir: /gscratch/portia/${paths.user}/biomech_model/Flybody/${dataset.name}/${version}
save_dir: ${paths.base_dir}/stac
log_dir:  ${paths.save_dir}/logs/
ckpt_dir: ${paths.save_dir}/ckpt/
fig_dir:  ${paths.save_dir}/figures/
data_dir: /gscratch/portia/${paths.user}/biomech_model/Flybody/datasets/${dataset.name}/${version}/

body_model_dir: /gscratch/portia/${paths.user}/Research/MyRepos/fruitfly_body_models/
project_dir: /gscratch/portia/${paths.user}/Research/MyRepos/