user: eabe

# set the directory where the output files get saved
cwd_dir:  /Users/${paths.user}/Research/MyRepos/Fly_tracking/
base_dir: /Users/${paths.user}/Research/data/biomech_model/Flybody/${dataset.name}/${version}
save_dir: ${paths.base_dir}/stac
log_dir:  ${paths.save_dir}/logs/
ckpt_dir: ${paths.save_dir}/ckpt/
fig_dir:  ${paths.save_dir}/figures/
data_dir: /Users/${paths.user}/Research/data/biomech_model/Flybody/datasets/${version}/

project_dir: /Users/${paths.user}/Research/MyRepos/