user: eabe

# set the directory where the output files get saved
cwd_dir:  /home/${paths.user}/Research/MyRepos/3d_tracking_dataset/
base_dir: /data2/users/${paths.user}/datasets/Johnson_lab/${dataset.name}/${version}
save_dir: ${paths.base_dir}/stac
log_dir:  ${paths.save_dir}/logs/
ckpt_dir: ${paths.save_dir}/ckpt/
fig_dir:  ${paths.save_dir}/figures/
data_dir: /data2/users/${paths.user}/datasets/Johnson_lab/${dataset.name}/${version}

body_model_dir: /home/${paths.user}/Research/MyRepos/fruitfly_body_models/
project_dir: /home/${paths.user}/Research/MyRepos/