mujoco:
  solver: "cg"
  iterations: 6
  ls_iterations: 6

paths:
  xml: "././models/rodent_stac.xml"
  fit_path: 
  transform_path:
  data_path: "/n/holylabs/LABS/olveczky_lab/holylfs02/Everyone/dannce_rig/dannce_ephys/art/2020_12_22_1/DANNCE/predict03/save_data_AVG.mat" 

stac:
  n_fit_frames: 500

test:
  skip_fit: False
  skip_transform: True
