mujoco:
  solver: "newton"
  iterations: 1
  ls_iterations: 4

paths:
  xml: "././models/rodent_stac.xml"
  fit_path: 
  transform_path:
  data_path: "/n/holylabs/LABS/olveczky_lab/holylfs02/Everyone/dannce_rig/dannce_ephys/art/2020_12_22_1/DANNCE/predict03/save_data_AVG.mat" 

stac:
  n_fit_frames: 500
  lr: 1.0e-2
  lr_init: 5.0e-2
  lr_end: 1.0e-5

test:
  skip_fit: False
  skip_transform: False
